# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XCFrameworkConsumer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCFrameworkConsumer
pod 'QuestionProCXFramework', :git => 'https://github.com/surveyanalyticscorp/ios-cx.git'
end
